//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoWallet
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankingInformation
    {
        public int UserId { get; set; }
        public Nullable<int> DebitBalance { get; set; }
        public Nullable<int> CryptoBalance { get; set; }
    
        public virtual PersonalInformation PersonalInformation { get; set; }
    }
}
